name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend-ci.yaml"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Cache Validation
        run: echo "Checking npm cache"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Cache Validation
        run: echo "Checking npm cache"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Cache Validation
        run: echo "Checking npm cache"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build Docker image
        run: docker build -t mp-frontend:latest .